import { createSlice } from "@reduxjs/toolkit";

const startingInfos = {
    fullName: "",
    emailAddress: "",
    profession: "",
    address: "",
    city: "",
    state: "",
    company: "",
    employer: "",
    role: "",
    workAddress: "",
    startDate: "",
    endDate: "",
    skill: "",
    schoolName: "",
    schoolLocation: "",
    degree: "",
    studyField: "",
    graduationMonth: "",
    graduationYear: "",
    phoneNumber: "",
    linkedinLink: "",
    twitterLink: "",
    githubLink: "",
    portfolioLink: "",
    certifications: "",
};

const infos = createSlice({
    name: "modify-infos",
    initialState: startingInfos,
    reducers: {
        setFullName: (state, action) => { state.fullName = action.payload },
        setEmailAddress: (state, action) => { state.emailAddress = action.payload },
        setProfession: (state, action) => { state.profession = action.payload },
        setAddress: (state, action) => { state.address = action.payload },
        setCity: (state, action) => { state.city = action.payload },
        setState: (state, action) => { state.state = action.payload },
        setCompany: (state, action) => { state.company = action.payload },
        setEmployer: (state, action) => { state.employer = action.payload },
        setRole: (state, action) => { state.role = action.payload },
        setWorkAddress: (state, action) => { state.workAddress = action.payload },
        setStartDate: (state, action) => { state.startDate = action.payload },
        setEndDate: (state, action) => { state.endDate = action.payload },
        setSkill: (state, action) => { state.skill = action.payload },
        setSchoolName: (state, action) => { state.schoolName = action.payload },
        setSchoolLocation: (state, action) => { state.schoolLocation = action.payload },
        setDegree: (state, action) => { state.degree = action.payload },
        setStudyField: (state, action) => { state.studyField = action.payload },
        setGraduationMonth: (state, action) => { state.graduationMonth = action.payload },
        setGraduationYear: (state, action) => { state.graduationYear = action.payload },
        setPhoneNumber: (state, action) => { state.phoneNumber = action.payload },
        setLinkedinLink: (state, action) => { state.linkedinLink = action.payload },
        setTwitterLink: (state, action) => { state.twitterLink = action.payload },
        setGithubLink: (state, action) => { state.githubLink = action.payload },
        setPortfolioLink: (state, action) => { state.portfolioLink = action.payload },
        setCertifications: (state, action) => { state.certifications = action.payload },
    },
});

export const {
    setFullName,
    setEmailAddress,
    setProfession,
    setAddress,
    setCity,
    setState,
    setCompany,
    setEmployer,
    setRole,
    setWorkAddress,
    setStartDate,
    setEndDate,
    setSkill,
    setSchoolName,
    setSchoolLocation,
    setDegree,
    setStudyField,
    setGraduationMonth,
    setGraduationYear,
    setPhoneNumber,
    setLinkedinLink,
    setTwitterLink,
    setGithubLink,
    setPortfolioLink,
    setCertifications,
} = infos.actions;

export default infos.reducer;